import * as fs from 'node:fs';
import * as path from 'node:path';
import _simpleGit, { type SimpleGit, type DiffResultTextFile } from 'simple-git';
import { MEMORY_FILES } from './memory.js';

const simpleGit = (_simpleGit as any).default ?? _simpleGit;

export interface DependencyChanges {
    added: string[];
    removed: string[];
    updated: string[];
}

export interface DiffSummary {
    commit: string;
    changed: DiffResultTextFile[];
    insertions: number;
    deletions: number;
    filesChanged: string[];
    addedFiles: string[];
    modifiedFiles: string[];
    deletedFiles: string[];
    diffs: string;
}

function getGit(rootDir: string): SimpleGit {
    return simpleGit(rootDir);
}

export function isGitRepo(rootDir: string): boolean {
    return fs.existsSync(path.join(rootDir, '.git'));
}

export function installPostCommitHook(rootDir: string): boolean {
    if (!isGitRepo(rootDir)) {
        return false;
    }

    const hookPath = path.join(rootDir, '.git', 'hooks', 'post-commit');
    const hookContent = `#!/bin/sh
# Auto-generated by ai-memory init
# Keep project memory in sync after every commit.

if command -v ai-memory >/dev/null 2>&1; then
  ai-memory sync >/dev/null 2>&1 || true
elif [ -x "./node_modules/.bin/ai-memory" ]; then
  ./node_modules/.bin/ai-memory sync >/dev/null 2>&1 || true
fi
`;

    fs.writeFileSync(hookPath, hookContent, { encoding: 'utf-8', mode: 0o755 });
    fs.chmodSync(hookPath, 0o755);
    return true;
}

export async function getLastSyncCommit(rootDir: string): Promise<string | null> {
    const syncFile = path.join(rootDir, MEMORY_FILES.lastSync);
    try {
        return fs.readFileSync(syncFile, 'utf-8').trim() || null;
    } catch {
        return null;
    }
}

export async function setLastSyncCommit(rootDir: string, hash: string): Promise<void> {
    const syncFile = path.join(rootDir, MEMORY_FILES.lastSync);
    fs.writeFileSync(syncFile, hash, 'utf-8');
}

export async function getCurrentCommit(rootDir: string): Promise<string> {
    const git = getGit(rootDir);
    const log = await git.log({ maxCount: 1 });
    return log.latest?.hash || 'HEAD';
}


function isMemoryInternalFile(filePath: string): boolean {
    return filePath === MEMORY_FILES.lastSync || filePath.startsWith(`${MEMORY_FILES.dir}/`);
}

function parseNameStatus(rawNameStatus: string): {
    addedFiles: string[];
    modifiedFiles: string[];
    deletedFiles: string[];
} {
    const addedFiles: string[] = [];
    const modifiedFiles: string[] = [];
    const deletedFiles: string[] = [];

    for (const line of rawNameStatus.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed) continue;

        const [status, ...fileParts] = trimmed.split(/\s+/);
        const file = fileParts.join(' ').trim();
        if (!file) continue;

        if (status.startsWith('A')) addedFiles.push(file);
        else if (status.startsWith('D')) deletedFiles.push(file);
        else modifiedFiles.push(file);
    }

    return { addedFiles, modifiedFiles, deletedFiles };
}

export async function getDiffSummary(rootDir: string, sinceCommit?: string): Promise<DiffSummary> {
    const git = getGit(rootDir);

    const since = sinceCommit || (await getLastSyncCommit(rootDir));
    const currentCommit = await getCurrentCommit(rootDir);

    let diff;
    let rawDiff: string;
    let rawNameStatus = '';

    if (since) {
        diff = await git.diffSummary([since, 'HEAD']);
        rawDiff = await git.diff([since, 'HEAD', '--stat']);
        rawNameStatus = await git.raw(['diff', '--name-status', since, 'HEAD']);
    } else {
        // First sync — diff against empty tree
        diff = await git.diffSummary(['HEAD~1', 'HEAD']).catch(async () => {
            // Single-commit repo — show all files
            return git.diffSummary(['--cached']);
        });
        rawDiff = await git.diff(['HEAD~1', 'HEAD', '--stat']).catch(() => '');
        rawNameStatus = await git.raw(['diff', '--name-status', 'HEAD~1', 'HEAD']).catch(() => '');
    }

    const { addedFiles, modifiedFiles, deletedFiles } = parseNameStatus(rawNameStatus);

    const filteredChanged = (diff.files as DiffResultTextFile[]).filter(file => !isMemoryInternalFile(file.file));
    const filteredAdded = addedFiles.filter(file => !isMemoryInternalFile(file));
    const filteredModified = modifiedFiles.filter(file => !isMemoryInternalFile(file));
    const filteredDeleted = deletedFiles.filter(file => !isMemoryInternalFile(file));

    return {
        commit: currentCommit,
        changed: filteredChanged,
        insertions: diff.insertions,
        deletions: diff.deletions,
        filesChanged: filteredChanged.map(f => f.file),
        addedFiles: filteredAdded,
        modifiedFiles: filteredModified,
        deletedFiles: filteredDeleted,
        diffs: rawDiff,
    };
}

function parsePackageDeps(content: string): Record<string, string> {
    try {
        const parsed = JSON.parse(content) as { dependencies?: Record<string, string>; devDependencies?: Record<string, string> };
        return {
            ...(parsed.dependencies || {}),
            ...(parsed.devDependencies || {}),
        };
    } catch {
        return {};
    }
}

export async function getDependencyChanges(rootDir: string, sinceCommit?: string): Promise<DependencyChanges> {
    const git = getGit(rootDir);
    const since = sinceCommit || (await getLastSyncCommit(rootDir));

    const currentPkg = fs.existsSync(path.join(rootDir, 'package.json'))
        ? fs.readFileSync(path.join(rootDir, 'package.json'), 'utf-8')
        : '{}';

    let previousPkg = '{}';

    if (since) {
        previousPkg = await git.raw(['show', `${since}:package.json`]).catch(() => '{}');
    } else {
        previousPkg = await git.raw(['show', 'HEAD~1:package.json']).catch(() => '{}');
    }

    const prev = parsePackageDeps(previousPkg);
    const cur = parsePackageDeps(currentPkg);

    const added: string[] = [];
    const removed: string[] = [];
    const updated: string[] = [];

    for (const dep of Object.keys(cur)) {
        if (!(dep in prev)) added.push(dep);
        else if (prev[dep] !== cur[dep]) updated.push(dep);
    }

    for (const dep of Object.keys(prev)) {
        if (!(dep in cur)) removed.push(dep);
    }

    return { added, removed, updated };
}

export async function getRecentChangedFiles(rootDir: string, n = 3): Promise<string[]> {
    const git = getGit(rootDir);
    const log = await git.log({ maxCount: n });

    const files = new Set<string>();
    for (const entry of log.all) {
        const diff = await git.diffSummary([`${entry.hash}~1`, entry.hash]).catch(() => null);
        if (diff) {
            for (const f of diff.files) {
                files.add(f.file);
            }
        }
    }

    return [...files];
}

export async function readFileContents(rootDir: string, filePaths: string[]): Promise<Record<string, string>> {
    const result: Record<string, string> = {};

    for (const fp of filePaths) {
        const fullPath = path.join(rootDir, fp);
        try {
            if (fs.existsSync(fullPath)) {
                const stat = fs.statSync(fullPath);
                if (stat.size > 50_000) {
                    result[fp] = `[File too large: ${(stat.size / 1024).toFixed(1)}KB]`;
                    continue;
                }
                result[fp] = fs.readFileSync(fullPath, 'utf-8');
            }
        } catch {
            // skip unreadable files
        }
    }

    return result;
}
